import { Shield, Car, Truck, Building, HardHat, Briefcase, Scale, Users } from "lucide-react"

export const allPracticeAreas = [
  {
    id: 1,
    title: "Personal Injury",
    slug: "/practice-areas/personal-injury",
    description: "Comprehensive legal representation for victims of accidents and injuries caused by negligence.",
    icon: <Shield className="h-10 w-10 text-yellow-500" aria-label="Personal Injury services icon" />,
    details: [
      "Catastrophic Injuries",
      "Traumatic Brain Injuries",
      "Spinal Cord Injuries",
      "Burn Injuries",
      "Wrongful Death",
      "Medical Malpractice",
    ],
  },
  {
    id: 2,
    title: "Car Accidents",
    slug: "/practice-areas/car-accidents",
    description: "Expert representation for victims of automobile accidents to secure maximum compensation.",
    icon: <Car className="h-10 w-10 text-yellow-500" aria-label="Car Accidents services icon" />,
    details: [
      "Head-On Collisions",
      "Rear-End Accidents",
      "T-Bone Accidents",
      "Multi-Vehicle Crashes",
      "Drunk Driving Accidents",
      "Distracted Driving Accidents",
    ],
  },
  {
    id: 3,
    title: "Truck Accidents",
    slug: "/practice-areas/truck-accidents",
    description: "Specialized legal support for victims of commercial truck and 18-wheeler accidents.",
    icon: <Truck className="h-10 w-10 text-yellow-500" aria-label="Truck Accidents services icon" />,
    details: [
      "18-Wheeler Accidents",
      "Delivery Truck Crashes",
      "Tanker Truck Accidents",
      "Logging Truck Accidents",
      "Underride Accidents",
      "Jackknife Accidents",
    ],
  },
  {
    id: 4,
    title: "Uber and Lyft Accidents",
    slug: "/practice-areas/uber-lyft-accidents",
    description: "Dedicated representation for passengers, drivers, and others injured in rideshare accidents.",
    icon: <Car className="h-10 w-10 text-yellow-500" aria-label="Rideshare Accidents services icon" />,
    details: [
      "Passenger Injuries",
      "Rideshare Driver Injuries",
      "Third-Party Vehicle Accidents",
      "Pedestrian Accidents",
      "Insurance Coverage Disputes",
      "App-On/App-Off Issues",
    ],
  },
  {
    id: 5,
    title: "Work Accidents",
    slug: "/practice-areas/work-accidents",
    description: "Helping injured workers navigate workers' compensation claims and third-party liability cases.",
    icon: <Briefcase className="h-10 w-10 text-yellow-500" aria-label="Work Accidents services icon" />,
    details: [
      "Workers' Compensation Claims",
      "Third-Party Liability Cases",
      "Machinery Accidents",
      "Toxic Exposure",
      "Repetitive Stress Injuries",
      "Workplace Falls",
    ],
  },
  {
    id: 6,
    title: "Construction Accidents",
    slug: "/practice-areas/construction-accidents",
    description:
      "Specialized representation for workers injured on construction sites and in building-related accidents.",
    icon: <HardHat className="h-10 w-10 text-yellow-500" aria-label="Construction Accidents services icon" />,
    details: [
      "Falls from Heights",
      "Scaffold Accidents",
      "Electrical Accidents",
      "Trench Collapses",
      "Equipment Malfunctions",
      "Struck-by Accidents",
    ],
  },
  {
    id: 7,
    title: "Slip and Fall Injuries",
    slug: "/practice-areas/slip-fall-injuries",
    description:
      "Holding property owners accountable for dangerous conditions that cause slip, trip, and fall injuries.",
    icon: <Building className="h-10 w-10 text-yellow-500" aria-label="Slip and Fall Injuries services icon" />,
    details: [
      "Wet Floor Accidents",
      "Uneven Surface Falls",
      "Inadequate Lighting Falls",
      "Staircase Accidents",
      "Parking Lot Falls",
      "Snow and Ice Accidents",
    ],
  },
  {
    id: 8,
    title: "White Collar Crimes",
    slug: "/practice-areas/white-collar-crimes",
    description:
      "Strategic defense against fraud, embezzlement, and other financial and business-related criminal charges.",
    icon: <Briefcase className="h-10 w-10 text-yellow-500" aria-label="White Collar Crimes services icon" />,
    details: ["Fraud Charges", "Embezzlement", "Money Laundering", "Tax Evasion", "Securities Fraud", "Identity Theft"],
  },
  {
    id: 9,
    title: "Immigration Law",
    slug: "/practice-areas/immigration-law",
    description:
      "Comprehensive immigration services including visas, green cards, citizenship, and deportation defense.",
    icon: <Scale className="h-10 w-10 text-yellow-500" aria-label="Immigration Law services icon" />,
    details: [
      "Family-Based Immigration",
      "Employment-Based Immigration",
      "Deportation Defense",
      "Asylum Applications",
      "Citizenship & Naturalization",
      "DACA & TPS",
    ],
  },
  {
    id: 10,
    title: "Class Actions",
    slug: "/practice-areas/class-actions",
    description: "Representing groups of individuals harmed by the same corporate misconduct or defective products.",
    icon: <Users className="h-10 w-10 text-yellow-500" aria-label="Class Actions services icon" />,
    details: [
      "Consumer Protection",
      "Defective Products",
      "Pharmaceutical Litigation",
      "Environmental Contamination",
      "Securities Fraud",
      "Employment Discrimination",
    ],
  },
]
